google/walt

android/WALT/app/build.gradle, android/WALT/app/src/main/java/org/chromium/latency/walt/ClockManager.java, android/WALT/app/src/main/java/org/chromium/latency/walt/FrontPageFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiFragment.java, android/WALT/app/src/main/res/drawable/ic_input_black_24dp.xml, android/WALT/app/src/main/res/drawable/ic_music_note_black_24dp.xml, android/WALT/app/src/main/res/drawable/ic_output_black_24dp.xml, android/WALT/app/src/main/res/layout/fragment_front_page.xml, android/WALT/app/src/main/res/layout/fragment_midi.xml, arduino/walt/walt.ino
As requested in issue #3.
Support for taking multiple samples and computing statistics will be added later.
=> Add basic MIDI latency testing

android/WALT/app/src/main/java/org/chromium/latency/walt/AudioFragment.java
=> Request permission at runtime to record audio on Marshmallow and above

android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java
=> Ask for permission to access external storage at runtime

android/WALT/app/build.gradle, android/WALT/build.gradle
This allows building the native library from within Android Studio
Fixes #4
=> Switch to experimental Gradle plugin

android/WALT/app/src/main/java/org/chromium/latency/walt/AudioFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/AudioTest.java, android/WALT/app/src/main/java/org/chromium/latency/walt/ClockManager.java, android/WALT/app/src/main/java/org/chromium/latency/walt/DiagnosticsFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/DragLatencyFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/LogFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiTest.java, android/WALT/app/src/main/java/org/chromium/latency/walt/ScreenResponseFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/SimpleLogger.java, android/WALT/app/src/main/java/org/chromium/latency/walt/TapLatencyFragment.java
This removes the dependence of the fragments on MainActivity and allows them to independently access the global state.
=> Refactor global state into singletons

android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java
=> Show Build.FINGERPRINT in the log

android/WALT/app/src/main/java/org/chromium/latency/walt/AutoRunFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/ClockManager.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiTest.java, android/WALT/app/src/main/res/layout/fragment_auto_run.xml
This should not impact normal usage of the app
=> Implement initial support for automated testing

android/WALT/app/src/main/java/org/chromium/latency/walt/AudioTest.java, android/WALT/app/src/main/java/org/chromium/latency/walt/ClockManager.java, android/WALT/app/src/main/java/org/chromium/latency/walt/DragLatencyFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiTest.java, android/WALT/app/src/main/java/org/chromium/latency/walt/ScreenResponseFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/TapLatencyFragment.java
Better error handling (fixing #6, although it still tries to sync with an unprogrammed WALT)
Simpler interface for handling trigger messages
=> Improvements to the interface for communication with WALT

android/WALT/app/src/main/java/org/chromium/latency/walt/ClockManager.java, android/WALT/app/src/main/res/values/strings.xml, arduino/walt/walt.ino
This ensures that the user will be notified appropriately when a
breaking change is made to the WALT protocol and an update must be
performed.
=> Add protocol versioning and version checking

android/WALT/app/build.gradle, android/WALT/app/src/main/java/org/chromium/latency/walt/NumberPickerPreference.java, android/WALT/app/src/main/java/org/chromium/latency/walt/PrefsFragment.java, android/WALT/app/src/main/res/layout/numberpicker_dialog.xml, android/WALT/app/src/main/res/values/attrs.xml, android/WALT/app/src/main/res/xml/preferences.xml
This will be used in the settings screen in a later version.
=> Create custom NumberPicker preference subclass

android/WALT/app/src/main/java/org/chromium/latency/walt/AudioTest.java, android/WALT/app/src/main/java/org/chromium/latency/walt/ClockManager.java, android/WALT/app/src/main/java/org/chromium/latency/walt/DragLatencyFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiTest.java, android/WALT/app/src/main/java/org/chromium/latency/walt/ScreenResponseFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/TapLatencyFragment.java
For the the warning is only saved as log message. Once we figure out some UI
for showing the results (like a histogram) the warning should be displayed as
part of that UI.
=> Check clock drift after each experiment

android/WALT/app/src/main/java/org/chromium/latency/walt/AudioFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java
When pressing volume buttons, media volume will be changed instead of the default (ringer volume). Also, when pressing the playback test button, the media volume will be set to 100%.
=> Make app control media volume, set volume to max for playback test

android/WALT/app/src/main/java/org/chromium/latency/walt/DragLatencyFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/FrontPageFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiTest.java, android/WALT/app/src/main/java/org/chromium/latency/walt/TapLatencyFragment.java, android/WALT/app/src/main/res/layout/fragment_diagnostics.xml, android/WALT/app/src/main/res/layout/fragment_front_page.xml, android/WALT/app/src/main/res/values/strings.xml
+ Unicode character for drag latency now works on Nexus 5/9
+ Clean up front page fragment (remove subtitles, remove unnecessary parent, remove extra dividers)
+ Print test type for MIDI
=> Clean up UI

android/WALT/app/src/main/java/org/chromium/latency/walt/AudioFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/AutoRunFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/BaseUsbConnection.java, android/WALT/app/src/main/java/org/chromium/latency/walt/DiagnosticsFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/DragLatencyFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/LogFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/ScreenResponseFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/SimpleLogger.java, android/WALT/app/src/main/java/org/chromium/latency/walt/UsMotionEvent.java, android/WALT/app/src/main/java/org/chromium/latency/walt/WaltConnection.java, android/WALT/app/src/main/java/org/chromium/latency/walt/WaltDevice.java, android/WALT/app/src/main/java/org/chromium/latency/walt/WaltTcpConnection.java, android/WALT/app/src/main/java/org/chromium/latency/walt/WaltUsbConnection.java, android/WALT/app/src/main/java/org/chromium/latency/walt/programmer/BootloaderConnection.java, android/WALT/app/src/main/java/org/chromium/latency/walt/programmer/FirmwareImage.java, android/WALT/app/src/main/java/org/chromium/latency/walt/programmer/Programmer.java, android/WALT/app/src/main/res/layout/activity_main.xml, android/WALT/app/src/main/res/values/strings.xml
... and small linter fixes too.
=> Rename member variables

android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java, android/WALT/app/src/main/res/layout/fragment_audio.xml, android/WALT/app/src/main/res/layout/fragment_diagnostics.xml, android/WALT/app/src/main/res/layout/fragment_screen_response.xml, android/WALT/app/src/main/res/values/strings.xml, android/WALT/app/src/main/res/values/styles.xml
Fixes the issue where the callback for getting microphone permissions is not called. Also makes the buttons a bit larger, and change some wording.
=> Fix microphone permission and UI tweaks

android/WALT/app/build.gradle, android/WALT/build.gradle
Ran all the tests on Nexus 9 with direct usb and they seem to work. This should also remove the popup in Android Studio to upgrade gradle.
=> Upgrade gradle and dependencies versions

android/WALT/app/src/main/java/org/chromium/latency/walt/AudioFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/AudioTest.java, android/WALT/app/src/main/java/org/chromium/latency/walt/BaseTest.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiTest.java, android/WALT/app/src/main/res/layout/fragment_audio.xml, android/WALT/app/src/main/res/layout/fragment_screen_response.xml, android/WALT/app/src/main/res/layout/line_chart.xml, android/WALT/app/src/main/res/values/color.xml, android/WALT/app/src/main/res/values/strings.xml, android/WALT/app/src/main/res/xml/preferences.xml
+ Draw recorded waveform (WALT -> app)
+ Change UI for AudioFragment to have stop/start buttons
+ Make recording threshold configurable in settings (default is 5000)
=> Waveform graph

android/WALT/app/src/main/java/org/chromium/latency/walt/AudioFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/AudioTest.java, android/WALT/app/src/main/java/org/chromium/latency/walt/BaseTest.java, android/WALT/app/src/main/java/org/chromium/latency/walt/CrashLogActivity.java, android/WALT/app/src/main/java/org/chromium/latency/walt/HistogramChart.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiTest.java, android/WALT/app/src/main/java/org/chromium/latency/walt/ScreenResponseFragment.java, android/WALT/app/src/main/res/layout/activity_crash_log.xml, android/WALT/app/src/main/res/layout/fragment_audio.xml, android/WALT/app/src/main/res/layout/fragment_midi.xml, android/WALT/app/src/main/res/layout/fragment_screen_response.xml, android/WALT/app/src/main/res/layout/histogram.xml, android/WALT/app/src/main/res/values/attrs.xml
+ Create custom HistogramChart view, which has BarChart and a close button
+ Add Histogram to Midi input/output, and Audio cold/continuous input/output
+ Allow scrolling in CrashLogActivity
+ Add feature to maximize/minimize chart to fullscreen
+ Adjust binWidth in settings
=> Add histograms to Audio and Midi tests

android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java, android/WALT/app/src/main/java/org/chromium/latency/walt/ScreenResponseFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/TapLatencyFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/TraceLogger.java, android/WALT/app/src/main/res/values/strings.xml, android/WALT/app/src/main/res/xml/preferences.xml
Write systrace events (text formatted to be accepted by Android importer) from tap and blink latency tests.
=> Write systrace events to file for traceview

pywalt/setup.py
Now people can do:
$ ./setup.py sdist
$ sudo ./setup.py install
=> pywalt: polish setup.py a bit more

android/WALT/app/build.gradle, android/WALT/app/src/main/java/org/chromium/latency/walt/HistogramChart.java, android/WALT/app/src/main/java/org/chromium/latency/walt/Utils.java, android/WALT/app/src/test/java/org/chromium/latency/walt/HistogramChartTest.java, android/WALT/app/src/test/java/org/chromium/latency/walt/TraceLoggerTest.java, android/WALT/app/src/test/java/org/chromium/latency/walt/UtilsTest.java
Uses JUnit, Mockito, and Powermock. These tests run on the local JVM and don't need an emulator/device. I'm hoping this will encourage more tests to be written in the future as the project goes into maintenance mode, and hopefully we can run these tests continuously in Travis or another CI.
=> Add unit tests

android/WALT/app/src/main/java/org/chromium/latency/walt/AudioTest.java, android/WALT/app/src/main/java/org/chromium/latency/walt/FrontPageFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/ScreenResponseFragment.java, android/WALT/app/src/main/res/layout/fragment_front_page.xml, android/WALT/app/src/main/res/values/color.xml
Address some TODOS and issue #61
=> Tackle some small todos

android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java
If the user presses the reprogram button without first pressing the white button on the Teensy, a dialog will appear. This dialog tells the user to press the white button, and when they do, will continue the reprogramming process.
=> Make reprogramming more user-friendly

android/WALT/app/src/main/java/org/chromium/latency/walt/AudioFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/DragLatencyFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/TapLatencyFragment.java, android/WALT/app/src/main/res/layout/fragment_audio.xml, android/WALT/app/src/main/res/layout/fragment_drag_latency.xml, android/WALT/app/src/main/res/layout/fragment_midi.xml, android/WALT/app/src/main/res/layout/fragment_screen_response.xml, android/WALT/app/src/main/res/layout/fragment_tap_latency.xml
=> Allow scrolling for tap/drag/midi test logs

android/WALT/app/src/main/java/org/chromium/latency/walt/AudioFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/DragLatencyFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/LogUploader.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MidiFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/ScreenResponseFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/TapLatencyFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/Utils.java, android/WALT/app/src/main/res/layout/dialog_upload.xml, android/WALT/app/src/main/res/values/strings.xml, android/WALT/app/src/main/res/xml/preferences.xml
User can click the upload icon in the toolbar to open a dialog. The user can enter the URL in this dialog, and the contents of the log will be posted to this URL.
=> Allow uploading log to URL

android/WALT/app/src/main/java/org/chromium/latency/walt/FastPathSurfaceView.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java, android/WALT/app/src/main/java/org/chromium/latency/walt/ScreenResponseFragment.java, android/WALT/app/src/main/res/layout/fragment_screen_response.xml, android/WALT/app/src/main/res/values/strings.xml
Initial implementation of fast-path graphics test
=> Implement fast-path graphics test

android/WALT/app/src/main/java/org/chromium/latency/walt/AccelerometerFragment.java, android/WALT/app/src/main/java/org/chromium/latency/walt/MainActivity.java, android/WALT/app/src/main/java/org/chromium/latency/walt/Utils.java, android/WALT/app/src/main/java/org/chromium/latency/walt/WaltDevice.java, android/WALT/app/src/main/res/layout/fragment_accelerometer.xml, android/WALT/app/src/main/res/layout/fragment_front_page.xml, android/WALT/app/src/test/java/org/chromium/latency/walt/AccelerometerFragmentTest.java, android/WALT/app/src/test/java/org/chromium/latency/walt/UtilsTest.java, arduino/walt/walt.ino
This adds a new test to measure the delta between the WALT accelerometer signal and the phone's accelerometer signal. It works by measuring both accelerometers' values over ~2 seconds, and then shifting the phone events backwards by 0.1ms increments to maximize cross-correlation. The shift with the maximum correlation between the 2 signals is the latency. This test is valid, as the latency of the WALT accelerometer is negligible.
=> Accelerometer latency test
